POST /api/login
Host: localhost:8080
Content-Type: application/json

{
    "id" : 1,
    "name" : "Phyllys Sowtere",
    "isProvider" : "1",
    "walletBalance" : "73.5",
    "email": "psowter0@fastcompany.com",
    "password": "1iYFwMf3"
}
### 

POST /api/register
Host: localhost:8080
Content-Type: application/json

{
    "id" : 21,
    "name" : "Subham Srivastava",
    "isProvider" : false,
    "walletBalance" : "12.23",
    "email": "subhamxx@gmail.com",
    "password": "1234"
}

### ORDERS ----------------------------------------------------------------------------------------------

GET /api/orders
Host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o
###

GET /api/orders
Host: localhost:8080

###

GET /api/orders/1
Host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o
###

GET /api/orders/21
Host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o
###

GET /api/orders?status=1
Host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o
###

POST /api/orders
Host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o
Content-Type: application/json

{
    "orderId" : 21,
    "userId" : 1,
    "serviceId" : 2,
	"adressId" : 1,
	"timestamp" : "2013-01-20",
	"orderStatus" : 2,
	"amount" : 23.43
}

###

POST /api/orders?order_id=21
Host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o
Content-Type: application/json

{
    "orderId" : 21,
    "userId" : 1,
    "serviceId" : 2,
	"adressId" : 1,
	"timestamp" : "2013-01-20",
	"orderStatus" : 1,
	"amount" : 23.43
}

### SERVICES ----------------------------------------------------------------------------------------------

GET /api/services
Host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o
###

GET /api/services/categories
Host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o
###

GET /api/services?category=consectetuer
Host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o
###

GET /api/services/2
Host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o
###

POST /api/services
Host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o
Content-Type: application/json

{
    "serviceId": 22,
    "providerId": 2,
    "addressId": 2,
    "isApproved": true,
    "category": "mattis",
    "description": "Morbi porttitor lorem id ligula.",
    "imageUrl": "http://dummyimage.com/122x100.png/ff4444/ffffff",
    "serviceRadius": 10.0,
    "price": 25.1,
    "ratingCount": 1000000,
    "completedOrders": 2222
}

###

POST /api/services/edit
Host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o
Content-Type: application/json

{
    "serviceId": 22,
    "providerId": 2,
    "addressId": 3,
    "isApproved": false,
    "category": "consectetuer",
    "description": "Morbi porttitor lorem id ligula. Suspendisse  ",
    "imageUrl": "http://dummyimage.com/122x100.png/ff4444/ffffff",
    "serviceRadius": 10.0,
    "price": 25.1,
    "ratingCount": 1000000,
    "completedOrders": 2222
}

###

GET /api/services/consectetuer/3
host: localhost:8080

### PAYMENT ----------------------------------------------------------------------------------------------

GET /api/wallet/balance
Host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o
###

POST /api/wallet/balance/add
Host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o
Amount : 20

###

POST /api/wallet/balance/withdraw
Host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o
Amount : 10

###

POST /api/wallet/balance/payment
host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o
Content-Type: application/json

{
    "orderId" : 1,
    "userId" : 1,
    "serviceId" : 2,
	"adressId" : 1,
	"timestamp" : "2013-01-20",
	"orderStatus" : 3,
	"amount" : 3.5
}


### ADDRESS ------------------------------------------------------------------------

GET /api/address
host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o

###

POST /api/address/edit
host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o
Content-Type: application/json

{
  "addressid": 21,
  "userId": 1,
  "lat": 150.7557791,
  "longi": -138.5709037
}

###

POST /api/address/add
host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o
Content-Type: application/json

{
  "addressid":25 ,
  "userId": 2,
  "lat": 50.7557791,
  "longi": 38.5709037
}

### REVIEW -----------------------------------------------------------------

GET /api/reviews/5
host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o

###

GET /api/reviews
host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o

###

POST /api/reviews
host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o
OrderStatus : 2
Content-Type: application/json

{
    "reviewId": 22,
    "userId": 1,
    "serviceId": 1,
    "rating": 5,
    "comment": "Vey bad product"
}

### CHATS -----------------------------------------------------------------

GET /api/chats/all
host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o

###

GET /api/chats?order_id=1
host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o

###

POST /api/chats
host: localhost:8080
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQaHlsbHlzIFNvd3RlcmUiLCJpZCI6MSwiZXhwIjoxNjIxMzg0Njk0LCJpYXQiOjE2MjEzMjQ2OTR9.4GKOhGuKjLX1MFLbHP9maqM1Y8yMTryCrUbWdZEf0-o
Content-Type: application/json

{
    "messageId": 22,
    "senderId": 4,
    "receiverId": 1,
    "content": "My Message",
    "timestamp": "2021-04-20"
}




