POST /api/login
Host: localhost:8080
Content-Type: application/json

{
    "id" : 1,
    "name" : "Zonnya Lorraine",
    "isProvider" : "0",
    "walletBalance" : "5.40",
    "email": "zlorraine0@devhub.com",
    "password": "MB86fpAFUS0"
}